### ISSUE TITLE
Define build approach for pymurtree

### ISSUE THREAD

**Issue by jurra** [MurTree/pymurtree#2]
- Should we download murtreecpp code using setup.py?
- Should we use git submodules?
- Should we automate a git clone?

**Comment by yiquintero** [comment]
We have tried two approches:
- Configuring murtree c++ repo as a submodule of the pymurtree repo.
  - Pro: no dependencies on GitPyhton
  - Con: clone recursively
- Downloading the murtree c++ source code using GitPython inside setup.py

Both solution work and produce the pymutree package correctly. 

For now we stay with GitPython but in the future we are open to switching to Git Submodules. Note: when switching to Git Submodules it is important to use a version reference of murtree

**Comment by jurra** [comment]
This can also be useful to read:
Glossary for distributing python code: https://packaging.python.org/en/latest/glossary/#term-source-distribution-or-sdist

**Comment by jurra** [comment]
I think this issue is closed, we have an approach currently.
