### ISSUE TITLE
Crash with max_depth=1 or 2 and no max_num_nodes specified

### ISSUE THREAD

**Issue by kjgm** [MurTree/pymurtree#40]
**Describe the bug**
When initializing the OptimalDecisionTreeClassifier with max_depth=1 or max_depth=2, the classifier crashes when calling fit, because max_num_nodes is automatically initialized with the default value 7, and max_depth=1 and max_num_nodes=7 is not a valid configuration

**To Reproduce**
Run the following python code:
```python
import pymurtree
import numpy

# Create training data
x = numpy.array([[0, 1, 0, 1], [1, 0, 0, 1], [1, 1, 0, 0]]) # features
y = numpy.array([5, 5, 4]) # labels

# Build tree classifier
model = pymurtree.OptimalDecisionTreeClassifier()
model.fit(x, y, max_depth=1)
```

**Expected behavior**
Automatically update max_num_nodes to 2^max_depth - 1, and warn about this change, then continue to run as normal

**Comment by yiquintero** [comment]
Thanks for reporting @kjgm! This issue relates to the MurTree solver itself, rather than to the Python wrapper. Could you please recreate the issue in the [MurTree repository](https://github.com/MurTree/murtree/issues)?
