### ISSUE TITLE
Predict feature implementation ideas

### ISSUE THREAD

**Issue by jurra** [MurTree/pymurtree#7]

**Comment by kjgm** [comment]
Once you have the tree extracted after Solve, you can use the extracted tree for prediction. The tree has a predict function.
See https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/tree/_tree.pyx line 804ff

**Comment by jurra** [comment]
@kjgm now we have two options, a predict method natively implemented in the pymurtree package, as well as the tree extraction feature.
