### ISSUE TITLE
Extract decision tree implementation ideas

### ISSUE THREAD

**Issue by jurra** [MurTree/pymurtree#8]
Help wanted:

How would you go about extracting the tree?
- Can you specify the format, for example what is a standard format people use to extract trees?
We found this example: https://mljar.com/blog/extract-rules-decision-tree/
- Is this what you mean by extracting the tree?

**Comment by kjgm** [comment]
My suggestion is to return a sklearn.Tree object
This object can then be used with standard visualization tools such as tree.export_text or sklearn.tree.export_graphviz

See https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/tree/_tree.pyx for how to construct a tree (line 536ff) and _add_node (line 762ff)
